### ISSUE TITLE
Ancient Warefare

### ISSUE THREAD

**Issue by Jerbearjerry** [Flawedspirit/Icehenge2#2]
What is the specific issue: All of the bearing recipes produce wooden bearings. These are needed 
                                          to complete some of the research.

What was happening when the issue arose: Progressing through the Ancient Warfare  research.

Which mod(s) were responsible (if known): Ancient Warfare

Steps to reproduce: Search up Wooden Iron or Steal Bearings in JEI

Link to crash log (if any): N/A

**Comment by Jerbearjerry** [comment]
The issue is actually with the bushing sets. Iron and Steel are unclickable while the wooden one shows all three recipes but all result in Wooden bushing set.

**Comment by Jerbearjerry** [comment]
The updated script worked but the rusult image is off still and depicted in the images.

https://puu.sh/E5y2K/8f55784ba4.png    Iron Bushing
https://puu.sh/E5y2r/7bae712f02.png     Steel Bushing

They both give the apropriate bushing but the result image is wrong.

**Comment by Flawedspirit** [comment]
Boneheaded oversight in the recipe conflict script on my part. The issue is fixed and will be available in a patch ASAP.
