### ISSUE TITLE
 Ancient Warfare Structure Scanner

### ISSUE THREAD

**Issue by Jerbearjerry** [Flawedspirit/Icehenge2#3]
Both the Structure Scanner block and Paper in JEI cannot be clicked and are uncrafteable. I went through the configs and scripts to see if it was disabled or removed but could not find anything.

**Comment by Flawedspirit** [comment]
Updated the mod, and checked around online for an answer as to why that is. Couldn't find anything. As of this very second I can only conclude that they don't have a recipe at all.
